[package]
name = "mb-data"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
mb-core.workspace = true
serde.workspace = true
arrow.workspace = true
parquet.workspace = true
serde_arrow.workspace = true
anyhow.workspace = true
chrono.workspace = true
tracing.workspace = true
